.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. polcoin_qt test_polcoin_qt
clean: FORCE
	$(MAKE) -C .. polcoin_qt_clean test_polcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_polcoin_qt_check
polcoin-qt polcoin-qt.exe: FORCE
	 $(MAKE) -C .. polcoin_qt
